spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_notice?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    show-sql: true
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
