# application.yml

spring:
  profiles:
    active: dev
  application:
    name: notice-service
  datasource:
    url: ${NOTICE_DATASOURCE_URL}
    username: ${NOTICE_DATASOURCE_USERNAME}
    password: ${NOTICE_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
